import { Product, Review } from "./types";
import { SHARED_SPIDER_SET } from "./sharedImages";

const IMG = [...SHARED_SPIDER_SET];

/** Encode paths that contain spaces (Glow dark / Spider Collection folders). */
const p = (path: string) => encodeURI(path);

const GLOW = {
  vol2: [
    p("/images/Nacklace/Glow dark nacklace/vol 2/vol 2.webp"),
    p("/images/Nacklace/Glow dark nacklace/vol 2/vol 2 thumbnail.webp"),
  ],
  vol4: [
    p("/images/Nacklace/Glow dark nacklace/vol 4/vol 4.webp"),
    p("/images/Nacklace/Glow dark nacklace/vol 4/vol 4 (2).webp"),
    p("/images/Nacklace/Glow dark nacklace/vol 4/vol 4 (3).webp"),
  ],
  vol5: [
    p("/images/Nacklace/Glow dark nacklace/vol 5/vol 5.webp"),
    p("/images/Nacklace/Glow dark nacklace/vol 5/vol 5 (2).webp"),
    p("/images/Nacklace/Glow dark nacklace/vol 5/vol 5 (3).webp"),
  ],
  vol6: [
    p("/images/Nacklace/Glow dark nacklace/vol 6/vol 6.webp"),
    p("/images/Nacklace/Glow dark nacklace/vol 6/vol 6 (2).webp"),
    p("/images/Nacklace/Glow dark nacklace/vol 6/vol 6 (3).webp"),
  ],
  vol7: [
    p("/images/Nacklace/Glow dark nacklace/vol 7/vol 7.webp"),
    p("/images/Nacklace/Glow dark nacklace/vol 7/vol 7 (2).webp"),
    p("/images/Nacklace/Glow dark nacklace/vol 7/vol 7 (3).webp"),
    p("/images/Nacklace/Glow dark nacklace/vol 7/vol 7 (4).webp"),
  ],
  vol9: [
    p("/images/Nacklace/Glow dark nacklace/vol 9/vol 9.webp"),
    p("/images/Nacklace/Glow dark nacklace/vol 9/vol 9 (2).webp"),
    p("/images/Nacklace/Glow dark nacklace/vol 9/vol 9 (3).webp"),
    p("/images/Nacklace/Glow dark nacklace/vol 9/vol 9 (4).webp"),
  ],
  vol10: [
    p("/images/Nacklace/Glow dark nacklace/vol 10/vol 10.webp"),
    p("/images/Nacklace/Glow dark nacklace/vol 10/vol 10 (2).webp"),
    p("/images/Nacklace/Glow dark nacklace/vol 10/vol 10 (3).webp"),
    p("/images/Nacklace/Glow dark nacklace/vol 10/vol 10 (4).webp"),
  ],
  vol11: [
    p("/images/Nacklace/Glow dark nacklace/vol 11/vol 11.webp"),
    p("/images/Nacklace/Glow dark nacklace/vol 11/vol 11 (2).webp"),
    p("/images/Nacklace/Glow dark nacklace/vol 11/vol 11 thumbnail.webp"),
  ],
};

const SPIDER = {
  vol1: [
    p("/images/Nacklace/Spider Collection/vol 1/vol 1.webp"),
    p("/images/Nacklace/Spider Collection/vol 1/vol 1 (2).webp"),
    p("/images/Nacklace/Spider Collection/vol 1/vol 1 (3).webp"),
  ],
  vol2: [
    p("/images/Nacklace/Spider Collection/vol 2/vol 2.webp"),
    p("/images/Nacklace/Spider Collection/vol 2/vol 2 (2).webp"),
  ],
  vol3: [
    p("/images/Nacklace/Spider Collection/vol 3/vol 3.webp"),
    p("/images/Nacklace/Spider Collection/vol 3/vol 3 (2).webp"),
  ],
  vol4: [
    p("/images/Nacklace/Spider Collection/vol 4/var 4.webp"),
    p("/images/Nacklace/Spider Collection/vol 4/var 4 (2).webp"),
  ],
  vol5: [
    p("/images/Nacklace/Spider Collection/vol 5/vol 5.webp"),
    p("/images/Nacklace/Spider Collection/vol 5/vol 5 (2).webp"),
  ],
  vol6: [
    p("/images/Nacklace/Spider Collection/vol 6/SaveClip.App_626440841_17886901317429824_4053387254417184985_n.webp"),
    p("/images/Nacklace/Spider Collection/vol 6/SaveClip.App_627311172_17886901326429824_4045215134332680882_n.webp"),
  ],
  vol7: [
    p("/images/Nacklace/Spider Collection/vol 7/vol 7.webp"),
    p("/images/Nacklace/Spider Collection/vol 7/vol 7 (2).webp"),
  ],
  vol8: [
    p("/images/Nacklace/Spider Collection/vol 8/vol 8.webp"),
    p("/images/Nacklace/Spider Collection/vol 8/vol 8 (2).webp"),
    p("/images/Nacklace/Spider Collection/vol 8/vol 8 (3).webp"),
  ],
  vol9: [
    p("/images/Nacklace/Spider Collection/vol 9/vol 9.webp"),
    p("/images/Nacklace/Spider Collection/vol 9/vol 9 (2).webp"),
    p("/images/Nacklace/Spider Collection/vol 9/vol 9 (3).webp"),
    p("/images/Nacklace/Spider Collection/vol 9/vol 9 (4).webp"),
  ],
  vol10: [
    p("/images/Nacklace/Spider Collection/vol 10/vol 10.webp"),
    p("/images/Nacklace/Spider Collection/vol 10/vol 10 (2).webp"),
    p("/images/Nacklace/Spider Collection/vol 10/vol 10 (3).webp"),
    p("/images/Nacklace/Spider Collection/vol 10/vol 10 (4).webp"),
  ],
};

const SILVER: Product["colors"][number] = { name: "Aged Sterling Silver", hex: "#B9B4AA" };
const CRIMSON: Product["colors"][number] = { name: "Crimson Bronze", hex: "#E50914" };
const OBSIDIAN: Product["colors"][number] = { name: "Obsidian Black", hex: "#1A0A0A" };
const GOLD: Product["colors"][number] = { name: "Antique Gold", hex: "#a08a52" };

function reviewsFor(seedName: string): Review[] {
  return [
    {
      id: `${seedName}-r1`,
      author: "M. Ashworth",
      rating: 5,
      date: "2026-05-12",
      title: "Heavier and finer than expected",
      body: "The filigree work is genuinely intricate in person. Sits perfectly at the collarbone and the finish hasn't dulled after weeks of wear.",
      verified: true,
    },
    {
      id: `${seedName}-r2`,
      author: "J. Okafor",
      rating: 4,
      date: "2026-04-28",
      title: "Gorgeous, arrived in beautiful packaging",
      body: "Exactly as pictured. Only wish the chain came slightly longer, but the clasp quality makes up for it.",
      verified: true,
    },
    {
      id: `${seedName}-r3`,
      author: "R. Delacroix",
      rating: 5,
      date: "2026-03-30",
      title: "A genuine conversation piece",
      body: "I get asked about this constantly. The oxidized detailing catches light in a way photos don't do justice to.",
      verified: false,
    },
  ];
}

export const CATEGORIES = [
  "Necklaces",
  "Glow Dark Necklace",
  "Bracelets",
  "Pant Hook Chain",
  "Denim Sling Bag",
  "Key Chain",
  "Jacket Pin",
  "Metal Hook Bookmark",
] as const;

export const COLLECTIONS = [
  {
    slug: "arachnid-requiem",
    name: "The Arachnid Requiem",
    description:
      "The founding collection. Gothic cathedral silhouettes cast in tarnished silver, built around the spider as a symbol of patience and quiet menace.",
    image: SPIDER.vol1[0],
  },
  {
    slug: "midnight-coven",
    name: "Midnight Coven",
    description:
      "A darker register — obsidian tones, glow-in-the-dark inlays, and severe geometry for pieces meant to be worn after sundown.",
    image: GLOW.vol2[0],
  },
  {
    slug: "gilded-relics",
    name: "Gilded Relics",
    description:
      "Warmer, antiqued gold tones softening the brand's gothic edge. Restored-catalog pieces reissued in limited runs.",
    image: IMG[0],
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "arachnid-requiem-necklace",
    name: "The Arachnid Requiem",
    category: "Necklaces",
    collection: "arachnid-requiem",
    price: 185,
    compareAtPrice: undefined,
    images: SPIDER.vol1,
    colors: [SILVER, OBSIDIAN],
    sizes: ["18\"", "20\"", "22\""],
    rating: 4.8,
    reviewCount: 132,
    isNew: true,
    isBestSeller: true,
    inStock: true,
    stockCount: 14,
    variantLabel: "Aged Sterling Silver",
    tagline: "A dark, ornate talisman for the modern age.",
    description:
      "Inspired by gothic cathedrals and natural predators, The Arachnid Requiem drapes a heart-shaped spider pendant from a fine ball chain. Every leg joint is hand-finished and the abdomen is hollowed to hold a hidden photoluminescent compound.",
    details: [
      "Cast in oxidized sterling silver",
      "Hand-etched gothic scrollwork",
      "Hollow abdomen with photoluminescent inlay",
      "Adjustable ball-chain clasp",
      "Serialized engraving on clasp",
    ],
    shippingInfo: "Ships in 2–4 business days in a cedar keepsake box. Free returns within 30 days.",
    reviews: reviewsFor("necklace-1"),
  },
  {
    id: "2",
    slug: "midnight-glow-necklace",
    name: "The Midnight Glow",
    category: "Glow Dark Necklace",
    collection: "midnight-coven",
    price: 210,
    compareAtPrice: 240,
    images: GLOW.vol7,
    colors: [OBSIDIAN, CRIMSON],
    sizes: ["18\"", "20\"", "22\""],
    rating: 4.9,
    reviewCount: 87,
    isNew: false,
    isBestSeller: true,
    inStock: true,
    stockCount: 6,
    variantLabel: "Crimson Variant",
    tagline: "The heart of the spider reveals its true nature in low light.",
    description:
      "A unique luminescent inlay catches and holds ambient light, releasing a slow crimson glow after dark. Cast from the same mould as the Requiem but finished in a deeper, near-black patina.",
    details: [
      "Deep obsidian patina finish",
      "Luminescent crimson inlay",
      "Reinforced jump rings for durability",
      "Comes with a polishing cloth",
    ],
    shippingInfo: "Ships in 2–4 business days. Free returns within 30 days.",
    reviews: reviewsFor("necklace-2"),
  },
  {
    id: "5",
    slug: "cathedral-cuff",
    name: "Cathedral Cuff",
    category: "Bracelets",
    collection: "arachnid-requiem",
    price: 152,
    images: [
      "/images/Nacklace/Bracelet/Bracelet 6/Bracelet 6.webp",
      "/images/Nacklace/Bracelet/Bracelet 6/Bracelet 6 (2).webp",
      "/images/Nacklace/Bracelet/Bracelet 6/Bracelet 6 (3).webp",
      "/images/Nacklace/Bracelet/Bracelet 6/Bracelet 6 (4).webp",
    ],
    colors: [SILVER, CRIMSON],
    sizes: ["S/M", "M/L"],
    rating: 4.5,
    reviewCount: 29,
    isNew: true,
    isBestSeller: false,
    inStock: true,
    stockCount: 11,
    variantLabel: "Aged Sterling Silver",
    tagline: "Architectural scrollwork wrapped around the wrist.",
    description:
      "An open cuff bracelet translating the cathedral motifs of the flagship necklace into a bold wrist piece. Adjustable open-back design fits most wrists.",
    details: [
      "Open-back adjustable cuff",
      "Oxidized sterling silver plate",
      "Padded interior for comfort",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("bracelet-1"),
  },
  {
    id: "6",
    slug: "coven-chain-bracelet",
    name: "Coven Chain Bracelet",
    category: "Bracelets",
    collection: "midnight-coven",
    price: 118,
    compareAtPrice: 140,
    images: [
      "/images/Nacklace/Bracelet/Bracelet 11/Bracelet 11.webp",
      "/images/Nacklace/Bracelet/Bracelet 11/Bracelet 11 (2).webp",
      "/images/Nacklace/Bracelet/Bracelet 11/Bracelet 11 (3).webp",
      "/images/Nacklace/Bracelet/Bracelet 11/Bracelet 11 (4).webp",
    ],
    colors: [OBSIDIAN, GOLD],
    sizes: ["S/M", "M/L"],
    rating: 4.4,
    reviewCount: 33,
    isNew: false,
    isBestSeller: true,
    inStock: true,
    stockCount: 19,
    variantLabel: "Obsidian Black",
    tagline: "A heavy ball-chain bracelet with a spider clasp.",
    description:
      "Matching the necklace's signature ball chain in bracelet form, secured with a miniature spider-shaped toggle clasp.",
    details: [
      "Matching ball-chain construction",
      "Spider toggle clasp",
      "Adjustable length",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("bracelet-2"),
  },
  {
    id: "9",
    slug: "obsidian-pendant-necklace",
    name: "Obsidian Pendant",
    category: "Necklaces",
    collection: "midnight-coven",
    price: 165,
    images: GLOW.vol4,
    colors: [OBSIDIAN],
    sizes: ["18\"", "20\"", "22\""],
    rating: 4.6,
    reviewCount: 44,
    isNew: true,
    isBestSeller: false,
    inStock: true,
    stockCount: 9,
    variantLabel: "Obsidian Black",
    tagline: "Severe geometry, minimal scrollwork.",
    description:
      "A pared-back interpretation of the house pendant for those who prefer sharp geometry over ornate filigree, finished entirely in matte black rhodium.",
    details: [
      "Matte black rhodium plating",
      "Simplified geometric silhouette",
      "Fine curb chain",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("necklace-3"),
  },
  {
    id: "10",
    slug: "relic-locket-necklace",
    name: "Relic Locket",
    category: "Necklaces",
    collection: "gilded-relics",
    price: 195,
    compareAtPrice: 225,
    images: [IMG[0], IMG[2], IMG[1]],
    colors: [GOLD, SILVER],
    sizes: ["18\"", "20\""],
    rating: 4.7,
    reviewCount: 38,
    isNew: false,
    isBestSeller: false,
    inStock: false,
    stockCount: 0,
    variantLabel: "Antique Gold",
    tagline: "A working locket restored from the archival catalog.",
    description:
      "One of our first designs, reissued from the original 1924 mould. The locket opens to hold a small keepsake and is finished with the same cathedral scrollwork as the rest of the line.",
    details: [
      "Functional hinged locket",
      "Antique gold vermeil",
      "Holds two small photographs",
    ],
    shippingInfo: "Currently out of stock — join the waitlist for restock alerts.",
    reviews: reviewsFor("necklace-4"),
  },
  {
    id: "15",
    slug: "glow-dark-crystal-vol5",
    name: "Glow Dark Crystal V",
    category: "Glow Dark Necklace",
    collection: "midnight-coven",
    price: 198,
    images: GLOW.vol5,
    colors: [OBSIDIAN, SILVER],
    sizes: ["18\"", "20\"", "22\""],
    rating: 4.7,
    reviewCount: 28,
    isNew: false,
    isBestSeller: true,
    inStock: true,
    stockCount: 12,
    variantLabel: "Glow Crystal",
    tagline: "A luminous crystal pendant that charges by day and glows after dark.",
    description:
      "A translucent crystal pendant on a fine silver chain, designed to absorb ambient light and release a soft glow in darkness.",
    details: [
      "Photoluminescent crystal pendant",
      "Fine silver-tone chain",
      "Lifestyle-ready everyday length",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("glow-5"),
  },
  {
    id: "16",
    slug: "glow-dark-crystal-vol6",
    name: "Glow Dark Crystal VI",
    category: "Glow Dark Necklace",
    collection: "midnight-coven",
    price: 205,
    images: GLOW.vol6,
    colors: [OBSIDIAN],
    sizes: ["18\"", "20\"", "22\""],
    rating: 4.8,
    reviewCount: 34,
    isNew: true,
    isBestSeller: true,
    inStock: true,
    stockCount: 10,
    variantLabel: "Glow Crystal",
    tagline: "Midnight crystal with a deeper, longer-lasting afterglow.",
    description:
      "An elevated glow-dark crystal piece with a denser luminescent core, finished for nightwear and low-light settings.",
    details: [
      "High-charge luminescent crystal",
      "Reinforced bail and clasp",
      "Cedar coffret packaging",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("glow-6"),
  },
  {
    id: "21",
    slug: "spider-collection-vol3",
    name: "Spider Bead Relic III",
    category: "Necklaces",
    collection: "arachnid-requiem",
    price: 175,
    images: SPIDER.vol3,
    colors: [SILVER, OBSIDIAN],
    sizes: ["18\"", "20\"", "22\""],
    rating: 4.7,
    reviewCount: 22,
    isNew: true,
    isBestSeller: false,
    inStock: true,
    stockCount: 11,
    variantLabel: "Spider Bead",
    tagline: "Beaded spider motif with glow accents and silver crosses.",
    description:
      "A beaded spider necklace mixing translucent glow beads, dark green accents, and silver cross charms around a central spider pendant.",
    details: [
      "Spider pendant centerpiece",
      "Glow and green bead mix",
      "Silver cross accents",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("spider-3"),
  },
  {
    id: "22",
    slug: "spider-collection-vol4",
    name: "Spider Bead Relic IV",
    category: "Necklaces",
    collection: "arachnid-requiem",
    price: 180,
    images: SPIDER.vol4,
    colors: [SILVER],
    sizes: ["18\"", "20\"", "22\""],
    rating: 4.6,
    reviewCount: 18,
    isNew: false,
    isBestSeller: true,
    inStock: true,
    stockCount: 10,
    variantLabel: "Spider Bead",
    tagline: "A denser bead arrangement around the house spider.",
    description:
      "A denser spider-collection strand with layered beads and the signature arachnid pendant at center.",
    details: [
      "Layered bead construction",
      "Central spider pendant",
      "Hand-linked silver spacers",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("spider-4"),
  },
  {
    id: "12",
    slug: "denim-hook-chain",
    name: "Denim Hook Chain",
    category: "Pant Hook Chain",
    collection: "arachnid-requiem",
    price: 145,
    compareAtPrice: undefined,
    images: [
      "/images/Nacklace/Pant Hook Chain/Denim hooks 1.webp",
      "/images/Nacklace/Pant Hook Chain/Denim hooks 1 (2).webp",
      "/images/Nacklace/Pant Hook Chain/Denim hooks 2.webp",
      "/images/Nacklace/Pant Hook Chain/Denim hooks 2 (2).webp",
      "/images/Nacklace/Pant Hook Chain/Denim hooks 3.webp",
      "/images/Nacklace/Pant Hook Chain/Denim hooks 3 (2).webp",
      "/images/Nacklace/Pant Hook Chain/Denim hooks 4.webp",
    ],
    colors: [SILVER],
    sizes: ["One Size"],
    rating: 4.7,
    reviewCount: 24,
    isNew: true,
    isBestSeller: false,
    inStock: true,
    stockCount: 8,
    variantLabel: "Aged Sterling Silver",
    tagline: "Handcrafted denim chain with gothic hardware.",
    description:
      "A dual-link belt loop chain combining heavy industrial snaps and gothic hardware. Designed to drape across pockets and waistbands.",
    details: [
      "Heavy duty snap hooks",
      "Gothic design accents",
      "Aged finish on solid alloy",
      "Overall length: 55cm",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("denim-hook"),
  },
  {
    id: "13",
    slug: "pant-hook-chain",
    name: "Gothic Pant Hook Chain",
    category: "Pant Hook Chain",
    collection: "arachnid-requiem",
    price: 165,
    compareAtPrice: undefined,
    images: [
      "/images/Nacklace/Pant Hook Chain/Pant Hook Chain 1.webp",
      "/images/Nacklace/Pant Hook Chain/Pant Hook Chain 2.webp",
      "/images/Nacklace/Pant Hook Chain/Pant Hook Chain 3.webp",
    ],
    colors: [SILVER],
    sizes: ["One Size"],
    rating: 4.8,
    reviewCount: 31,
    isNew: true,
    isBestSeller: true,
    inStock: true,
    stockCount: 5,
    variantLabel: "Aged Sterling Silver",
    tagline: "Gothic steel links for cargo or trouser drapes.",
    description:
      "A triple-layered metallic drape designed for cargo pants and heavy trousers. Completed with signature spring-loaded clasps and handcrafted gothic details.",
    details: [
      "Triple-layered chain design",
      "Oxidized gothic metal clasp details",
      "Solid alloy structure with sterling silver finish",
      "Overall length: 60cm",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("pant-hook"),
  },
  {
    id: "14",
    slug: "denim-sling-bag-i",
    name: "Denim Sling Bag I",
    category: "Denim Sling Bag",
    collection: "arachnid-requiem",
    price: 120,
    compareAtPrice: undefined,
    images: [
      "/images/Nacklace/Denim Sling Bag/Bag 1/Denim sling bag 1.webp",
      "/images/Nacklace/Denim Sling Bag/Bag 1/Denim sling bag 1 (2).webp",
      "/images/Nacklace/Denim Sling Bag/Bag 1/Denim sling bag 1 (3).webp",
      "/images/Nacklace/Denim Sling Bag/Bag 1/Denim sling bag 1 (4).webp",
    ],
    colors: [SILVER],
    sizes: ["One Size"],
    rating: 4.6,
    reviewCount: 12,
    isNew: true,
    isBestSeller: false,
    inStock: true,
    stockCount: 6,
    variantLabel: "Indigo Denim",
    tagline: "Heavyweight utility sling with signature branding.",
    description:
      "A rugged, custom-washed denim sling bag featuring heavy zippers and signature gothic branding. Built for durability and style.",
    details: [
      "Custom washed denim construction",
      "Heavy duty hardware & zip pulls",
      "Signature gothic interior lining",
      "Adjustable shoulder strap",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("denim-bag-1"),
  },
  {
    id: "15-bag",
    slug: "denim-sling-bag-ii",
    name: "Denim Sling Bag II",
    category: "Denim Sling Bag",
    collection: "arachnid-requiem",
    price: 135,
    compareAtPrice: undefined,
    images: [
      "/images/Nacklace/Denim Sling Bag/Bag 2/Denim sling bag 2.webp",
      "/images/Nacklace/Denim Sling Bag/Bag 2/Denim sling bag 2 (2).webp",
      "/images/Nacklace/Denim Sling Bag/Bag 2/Denim sling bag 2 (3).webp",
      "/images/Nacklace/Denim Sling Bag/Bag 2/Denim sling bag 2 (4).webp",
    ],
    colors: [SILVER],
    sizes: ["One Size"],
    rating: 4.8,
    reviewCount: 19,
    isNew: true,
    isBestSeller: true,
    inStock: true,
    stockCount: 4,
    variantLabel: "Acid Wash Denim",
    tagline: "Acid wash utility sling with gothic details.",
    description:
      "An acid-washed utility sling bag featuring multiple compartments and hand-finished gothic details. Crafted for daily relic carry.",
    details: [
      "Acid-washed canvas & denim outer",
      "Multiple compartments with secure zip closures",
      "Hand-finished metallic details",
      "Adjustable webbed shoulder strap",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("denim-bag-2"),
  },
  {
    id: "16-bead",
    slug: "gothic-bead-bracelet",
    name: "Gothic Bead Bracelet",
    category: "Bracelets",
    collection: "arachnid-requiem",
    price: 85,
    compareAtPrice: undefined,
    images: ["/images/Nacklace/Bracelet/Bracelet 1.webp"],
    colors: [SILVER],
    sizes: ["S/M", "M/L"],
    rating: 4.6,
    reviewCount: 14,
    isNew: true,
    isBestSeller: false,
    inStock: true,
    stockCount: 12,
    variantLabel: "Aged Sterling Silver",
    tagline: "Handcrafted bead bracelet with dark metal spacers.",
    description: "A delicate yet distinct hand-strung bead bracelet, combining aged steel beads with gothic spacer links.",
    details: ["Aged steel beads", "Handcrafted spacer links", "Elastic stretch fit", "Hand-finished components"],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("gothic-bead"),
  },
  {
    id: "17",
    slug: "oxidized-link-bracelet",
    name: "Oxidized Link Bracelet",
    category: "Bracelets",
    collection: "arachnid-requiem",
    price: 95,
    compareAtPrice: undefined,
    images: ["/images/Nacklace/Bracelet/Bracelet 2.webp"],
    colors: [SILVER],
    sizes: ["S/M", "M/L"],
    rating: 4.5,
    reviewCount: 18,
    isNew: false,
    isBestSeller: false,
    inStock: true,
    stockCount: 8,
    variantLabel: "Aged Sterling Silver",
    tagline: "Thick oxidized links with a vintage clasp.",
    description: "Heavy oxidized metal links paired with a secure vintage clasp. Perfect for layering or wearing standalone.",
    details: ["Heavy metal link construction", "Oxidized rustic finish", "Secure signature clasp", "One size fits most"],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("oxidized-link"),
  },
  {
    id: "18",
    slug: "skull-spikes-bracelet",
    name: "Skull & Spikes Bracelet",
    category: "Bracelets",
    collection: "midnight-coven",
    price: 110,
    compareAtPrice: 130,
    images: ["/images/Nacklace/Bracelet/Bracelet 3.webp"],
    colors: [SILVER],
    sizes: ["S/M", "M/L"],
    rating: 4.8,
    reviewCount: 22,
    isNew: true,
    isBestSeller: true,
    inStock: true,
    stockCount: 5,
    variantLabel: "Aged Sterling Silver",
    tagline: "Gothic skulls and miniature spikes.",
    description: "A rebellious statement piece detailed with miniature skull beads and subtle gothic spikes along the band.",
    details: ["Detailed skull beads", "Gothic spike accents", "Tough industrial cord core", "Handmade detailing"],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("skull-spikes"),
  },
  {
    id: "19",
    slug: "spiny-link-chain",
    name: "Spiny Link Chain",
    category: "Bracelets",
    collection: "midnight-coven",
    price: 105,
    compareAtPrice: undefined,
    images: ["/images/Nacklace/Bracelet/Bracelet 4.webp"],
    colors: [SILVER],
    sizes: ["S/M", "M/L"],
    rating: 4.7,
    reviewCount: 11,
    isNew: true,
    isBestSeller: false,
    inStock: true,
    stockCount: 9,
    variantLabel: "Aged Sterling Silver",
    tagline: "Interlinked spiny chain bands.",
    description: "Sharp, spiny links connect to form a bold industrial chain bracelet with a high-shine aged silver coating.",
    details: ["Spiny link chain design", "Aged silver plating", "Spring-loaded hook closure", "Overall length: 21cm"],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("spiny-link"),
  },
  {
    id: "20",
    slug: "cathedral-arch-bracelet",
    name: "Cathedral Arch Bracelet",
    category: "Bracelets",
    collection: "arachnid-requiem",
    price: 125,
    compareAtPrice: undefined,
    images: ["/images/Nacklace/Bracelet/Bracelet 5.webp"],
    colors: [SILVER],
    sizes: ["S/M", "M/L"],
    rating: 4.6,
    reviewCount: 15,
    isNew: false,
    isBestSeller: true,
    inStock: true,
    stockCount: 6,
    variantLabel: "Aged Sterling Silver",
    tagline: "Engraved gothic arches linked together.",
    description: "Interlinking panels showing hand-engraved gothic cathedral arches, creating a substantial weight on the wrist.",
    details: ["Engraved arch panels", "Heavyweight structure", "Concealed push clasp", "Premium presentation box included"],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("cathedral-arch"),
  },
  {
    id: "21-charm",
    slug: "aged-charm-bracelet",
    name: "Aged Charm Bracelet",
    category: "Bracelets",
    collection: "arachnid-requiem",
    price: 115,
    compareAtPrice: undefined,
    images: [
      "/images/Nacklace/Bracelet/Bracelet 7/Bracelet 7.webp",
      "/images/Nacklace/Bracelet/Bracelet 7/Bracelet 7 (2).webp",
    ],
    colors: [SILVER],
    sizes: ["S/M", "M/L"],
    rating: 4.8,
    reviewCount: 20,
    isNew: true,
    isBestSeller: false,
    inStock: true,
    stockCount: 7,
    variantLabel: "Aged Sterling Silver",
    tagline: "Gothic charms suspended from a heavy chain.",
    description: "A heavyweight chain bracelet suspending various relic charms, including crosses and spider symbols.",
    details: ["Heavy link base chain", "Multiple gothic relic charms", "Tarnish-resistant finish", "Secure clasp"],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("aged-charm"),
  },
  {
    id: "22-wrap",
    slug: "cobweb-wrap-bracelet",
    name: "Cobweb Wrap Bracelet",
    category: "Bracelets",
    collection: "midnight-coven",
    price: 130,
    compareAtPrice: undefined,
    images: [
      "/images/Nacklace/Bracelet/Bracelet 8/Bracelet 8.webp",
      "/images/Nacklace/Bracelet/Bracelet 8/Bracelet 8 (2).webp",
    ],
    colors: [SILVER],
    sizes: ["S/M", "M/L"],
    rating: 4.7,
    reviewCount: 26,
    isNew: false,
    isBestSeller: true,
    inStock: true,
    stockCount: 4,
    variantLabel: "Aged Sterling Silver",
    tagline: "Intricate cobweb wrap pattern.",
    description: "Fine, interwoven wirework recreating the patient geometry of a cobweb, wrapped around a rigid steel core.",
    details: ["Handcrafted wire cobweb design", "Rigid internal wire core", "Adjustable wrap fit", "Comfort-rounded edges"],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("cobweb-wrap"),
  },
  {
    id: "23",
    slug: "dark-relic-bangle",
    name: "Dark Relic Bangle",
    category: "Bracelets",
    collection: "gilded-relics",
    price: 140,
    compareAtPrice: 160,
    images: [
      "/images/Nacklace/Bracelet/Bracelet 9/Bracelet 9.webp",
      "/images/Nacklace/Bracelet/Bracelet 9/Bracelet 9 (2).webp",
    ],
    colors: [SILVER],
    sizes: ["S/M", "M/L"],
    rating: 4.9,
    reviewCount: 17,
    isNew: true,
    isBestSeller: true,
    inStock: true,
    stockCount: 3,
    variantLabel: "Aged Sterling Silver",
    tagline: "A solid gothic bangle with deep etchings.",
    description: "A solid, circular metal bangle featuring deep-etched gothic carvings and finished with an antique tarnish.",
    details: ["Solid metal bangle structure", "Deep-etched antique carvings", "Hand-finished tarnish", "Diameter: 6.5cm"],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("dark-relic"),
  },
  {
    id: "24",
    slug: "skeletal-spine-bracelet",
    name: "Skeletal Spine Bracelet",
    category: "Bracelets",
    collection: "midnight-coven",
    price: 145,
    compareAtPrice: undefined,
    images: [
      "/images/Nacklace/Bracelet/Bracelet 10/Bracelet 10.webp",
      "/images/Nacklace/Bracelet/Bracelet 10/Bracelet 10 (2).webp",
    ],
    colors: [SILVER],
    sizes: ["S/M", "M/L"],
    rating: 4.8,
    reviewCount: 30,
    isNew: true,
    isBestSeller: false,
    inStock: true,
    stockCount: 5,
    variantLabel: "Aged Sterling Silver",
    tagline: "Skeletal spine link configuration.",
    description: "Interlinked joints styled after a skeletal spine, giving an organic yet severe drape to the wrist.",
    details: ["Skeletal spine joint aesthetics", "Individually linked joints", "Aged silver patina", "Fold-over secure clasp"],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("skeletal-spine"),
  },
  {
    id: "25",
    slug: "gothic-jacket-pin",
    name: "Gothic Jacket Pin",
    category: "Jacket Pin",
    collection: "arachnid-requiem",
    price: 45,
    compareAtPrice: undefined,
    images: [
      "/images/Nacklace/Jacket pin/Jacket pin 1.webp",
      "/images/Nacklace/Jacket pin/Jacket pin 1 (2).webp",
      "/images/Nacklace/Jacket pin/Jacket pin 1 (3).webp",
      "/images/Nacklace/Jacket pin/Jacket pin 1 (4).webp",
    ],
    colors: [SILVER],
    sizes: ["One Size"],
    rating: 4.8,
    reviewCount: 16,
    isNew: true,
    isBestSeller: true,
    inStock: true,
    stockCount: 10,
    variantLabel: "Aged Sterling Silver",
    tagline: "Gothic brooch with intricate silver scrollwork.",
    description:
      "A hand-finished gothic brooch pin designed to adorn jackets, backpacks, or heavy lapels. Features highly detailed silver scrollwork and double pin clasps for security.",
    details: [
      "Solid alloy with aged silver finish",
      "Highly detailed gothic scrollwork",
      "Double pin back locks",
      "Size: 4.5cm x 4.5cm",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("jacket-pin"),
  },
  {
    id: "26",
    slug: "metal-hook-bookmark-i",
    name: "Metal Hook Bookmark I",
    category: "Metal Hook Bookmark",
    collection: "arachnid-requiem",
    price: 38,
    compareAtPrice: undefined,
    images: [
      "/images/Nacklace/Metal hook bookmark/Metal hook bookmark 1/Metal hook bookmark 1.webp",
      "/images/Nacklace/Metal hook bookmark/Metal hook bookmark 1/Metal hook bookmark 1 (2).webp",
      "/images/Nacklace/Metal hook bookmark/Metal hook bookmark 1/Metal hook bookmark 1 (3).webp",
    ],
    colors: [SILVER],
    sizes: ["One Size"],
    rating: 4.7,
    reviewCount: 9,
    isNew: true,
    isBestSeller: false,
    inStock: true,
    stockCount: 15,
    variantLabel: "Aged Sterling Silver",
    tagline: "Antique silver hook bookmark with scrollwork.",
    description:
      "An antique silver-plated metal hook bookmark, featuring intricate gothic carvings that drape beautifully over book spines.",
    details: [
      "Heavy duty alloy bookmark hook",
      "Antique silver scrollwork details",
      "Rounded edge prevents page damage",
      "Length: 12cm",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("bookmark-1"),
    video: "/images/Nacklace/Metal hook bookmark/Metal hook bookmark 1/Metal hook bookmark video.mp4",
  },
  {
    id: "27",
    slug: "metal-hook-bookmark-ii",
    name: "Metal Hook Bookmark II",
    category: "Metal Hook Bookmark",
    collection: "midnight-coven",
    price: 42,
    compareAtPrice: undefined,
    images: [
      "/images/Nacklace/Metal hook bookmark/Metal hook bookmark 2/Metal hook bookmark 2.webp",
      "/images/Nacklace/Metal hook bookmark/Metal hook bookmark 2/Metal hook bookmark 2 (2).webp",
      "/images/Nacklace/Metal hook bookmark/Metal hook bookmark 2/Metal hook bookmark 2 (3).webp",
    ],
    colors: [SILVER],
    sizes: ["One Size"],
    rating: 4.8,
    reviewCount: 14,
    isNew: true,
    isBestSeller: true,
    inStock: true,
    stockCount: 8,
    variantLabel: "Aged Sterling Silver",
    tagline: "Dagger-style bookmark with oxidized finish.",
    description:
      "A darker, oxidized finish bookmark featuring severe geometry and a detailed dagger-like hook silhouette.",
    details: [
      "Dark oxidized silver coating",
      "Dagger style geometric details",
      "Polished hooks for page safety",
      "Length: 12.5cm",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("bookmark-2"),
    video: "/images/Nacklace/Metal hook bookmark/Metal hook bookmark 2/Metal hook bookmark 2 video.mp4",
  },
  {
    id: "28",
    slug: "metal-hook-bookmark-iii",
    name: "Metal Hook Bookmark III",
    category: "Metal Hook Bookmark",
    collection: "arachnid-requiem",
    price: 45,
    compareAtPrice: undefined,
    images: [
      "/images/Nacklace/Metal hook bookmark/Metal hook bookmark 3/Metal hook bookmark 3.webp",
      "/images/Nacklace/Metal hook bookmark/Metal hook bookmark 3/Metal hook bookmark 3 (2).webp",
      "/images/Nacklace/Metal hook bookmark/Metal hook bookmark 3/Metal hook bookmark 3 (3).webp",
    ],
    colors: [SILVER],
    sizes: ["One Size"],
    rating: 4.9,
    reviewCount: 20,
    isNew: true,
    isBestSeller: true,
    inStock: true,
    stockCount: 6,
    variantLabel: "Aged Sterling Silver",
    tagline: "Metal bookmark with spider charm.",
    description:
      "A premium engraved metal hook bookmark adorned with a spider toggle charm at the top. The ultimate accessory for your grimoires.",
    details: [
      "Hand-cast silver alloy bookmark",
      "Interlinking spider toggle charm",
      "Engraved spine pattern",
      "Length: 13cm",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("bookmark-3"),
    video: "/images/Nacklace/Metal hook bookmark/Metal hook bookmark 3/Metal hook bookmark 3 video.mp4",
  },
  {
    id: "29",
    slug: "gothic-keychain-i",
    name: "Gothic Key Chain I",
    category: "Key Chain",
    collection: "arachnid-requiem",
    price: 50,
    compareAtPrice: undefined,
    images: [
      "/images/Nacklace/Keychain/Keychain 1/Keychain 1.webp",
      "/images/Nacklace/Keychain/Keychain 1/Keychain 1 (2).webp",
    ],
    colors: [SILVER],
    sizes: ["One Size"],
    rating: 4.7,
    reviewCount: 15,
    isNew: true,
    isBestSeller: false,
    inStock: true,
    stockCount: 10,
    variantLabel: "Aged Sterling Silver",
    tagline: "Industrial key chain with skull medallion.",
    description:
      "A heavy-link keychain featuring custom industrial snaps, a detailed spider charm, and a high-visibility yellow skull medallion.",
    details: [
      "Heavy industrial snap hooks",
      "Spider charm pendant",
      "Yellow skull acrylic medallion",
      "Overall length: 18cm",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("keychain-1"),
    video: "/images/Nacklace/Keychain/Keychain 1/Keychain 1 video.mp4",
  },
  {
    id: "30",
    slug: "gothic-keychain-ii",
    name: "Gothic Key Chain II",
    category: "Key Chain",
    collection: "midnight-coven",
    price: 45,
    compareAtPrice: undefined,
    images: [
      "/images/Nacklace/Keychain/Keychain 2/Keychain 2.webp",
      "/images/Nacklace/Keychain/Keychain 2/Keychain 2 (2).webp",
    ],
    colors: [SILVER],
    sizes: ["One Size"],
    rating: 4.6,
    reviewCount: 12,
    isNew: true,
    isBestSeller: true,
    inStock: true,
    stockCount: 8,
    variantLabel: "Aged Sterling Silver",
    tagline: "Hand-finished skull key clasp.",
    description:
      "An antique-finished skull key clasp, hand-finished with deep-etched skeletal components. Secures all keys on a heavy ring.",
    details: [
      "Carved skull hook mechanism",
      "Heavy duty split keyring",
      "Hand-finished black tarnish",
      "Length: 10cm",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("keychain-2"),
  },
  {
    id: "31",
    slug: "gothic-keychain-iii",
    name: "Gothic Key Chain III",
    category: "Key Chain",
    collection: "midnight-coven",
    price: 48,
    compareAtPrice: undefined,
    images: [
      "/images/Nacklace/Keychain/Keychain 3/Keychain 3.webp",
      "/images/Nacklace/Keychain/Keychain 3/Keychain 3 (2).webp",
    ],
    colors: [SILVER],
    sizes: ["One Size"],
    rating: 4.8,
    reviewCount: 22,
    isNew: true,
    isBestSeller: false,
    inStock: true,
    stockCount: 12,
    variantLabel: "Aged Sterling Silver",
    tagline: "Dual-ended snap cross key chain.",
    description:
      "Dual-ended secure snaps holding a custom molded cross and aged key rings, keeping keys and clips perfectly separated.",
    details: [
      "Dual spring snap hooks",
      "Custom gothic cross charm",
      "Extra wide key loops",
      "Length: 15cm",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("keychain-3"),
    video: "/images/Nacklace/Keychain/Keychain 3/Keychain 3 video.mp4",
  },
  {
    id: "32",
    slug: "gothic-keychain-iv",
    name: "Gothic Key Chain IV",
    category: "Key Chain",
    collection: "arachnid-requiem",
    price: 55,
    compareAtPrice: undefined,
    images: [
      "/images/Nacklace/Keychain/Keychain 4/Key chain 4.webp",
      "/images/Nacklace/Keychain/Keychain 4/Key chain 4 (2).webp",
    ],
    colors: [SILVER],
    sizes: ["One Size"],
    rating: 4.9,
    reviewCount: 31,
    isNew: true,
    isBestSeller: true,
    inStock: true,
    stockCount: 4,
    variantLabel: "Aged Sterling Silver",
    tagline: "Carabiner key chain with multi-chain links.",
    description:
      "A triple-chain hardware piece featuring carabiners, spring clasps, and detailed metal charms for belt-loop hanging.",
    details: [
      "Stainless steel carabiner clip",
      "Triple chain links",
      "Gothic design accents",
      "Length: 20cm",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("keychain-4"),
    video: "/images/Nacklace/Keychain/Keychain 4/Keychain 4 video.mp4",
  },
  {
    id: "33",
    slug: "gothic-keychain-v",
    name: "Gothic Key Chain V",
    category: "Key Chain",
    collection: "midnight-coven",
    price: 52,
    compareAtPrice: undefined,
    images: [
      "/images/Nacklace/Keychain/Keychain 5/Keychain 5.webp",
      "/images/Nacklace/Keychain/Keychain 5/Keychain 5 (2).webp",
    ],
    colors: [SILVER],
    sizes: ["One Size"],
    rating: 4.8,
    reviewCount: 18,
    isNew: true,
    isBestSeller: true,
    inStock: true,
    stockCount: 7,
    variantLabel: "Aged Sterling Silver",
    tagline: "Heavy skull clasp hardware loop.",
    description:
      "A solid-link hardware loop designed to hang from belt loops, finished with an industrial skull clasp and thick metal ring.",
    details: [
      "Solid alloy links",
      "Industrial skull lock clasp",
      "Aged metallic finish",
      "Length: 16cm",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("keychain-5"),
    video: "/images/Nacklace/Keychain/Keychain 5/Keychain 5 video.mp4",
  },
  {
    id: "34",
    slug: "gothic-keychain-vi",
    name: "Gothic Key Chain VI",
    category: "Key Chain",
    collection: "arachnid-requiem",
    price: 45,
    compareAtPrice: undefined,
    images: [
      "/images/Nacklace/Keychain/Keychain 6/Keychain 6.webp",
      "/images/Nacklace/Keychain/Keychain 6/Keychain 6 (2).webp",
    ],
    colors: [SILVER],
    sizes: ["One Size"],
    rating: 4.7,
    reviewCount: 14,
    isNew: false,
    isBestSeller: false,
    inStock: true,
    stockCount: 15,
    variantLabel: "Aged Sterling Silver",
    tagline: "Gothic ball-chain keyring hanger.",
    description:
      "A clean gothic key hanger using heavy steel ball-chains and detailed metal hardware for a minimal but dark presentation.",
    details: [
      "Heavy duty ball chain links",
      "Engraved clasp locks",
      "Solid alloy Split ring",
      "Length: 12cm",
    ],
    shippingInfo: "Ships in 2–4 business days.",
    reviews: reviewsFor("keychain-6"),
    video: "/images/Nacklace/Keychain/Keychain 6/Keychain 6 video.mp4",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return PRODUCTS.filter(
    (p) => p.id !== product.id && (p.category === product.category || p.collection === product.collection)
  ).slice(0, limit);
}

export function getBestSellers(limit?: number): Product[] {
  const items = PRODUCTS.filter((p) => p.isBestSeller);
  return limit ? items.slice(0, limit) : items;
}

export function getNewArrivals(limit?: number): Product[] {
  const items = PRODUCTS.filter((p) => p.isNew);
  return limit ? items.slice(0, limit) : items;
}

export function getProductsByCategory(category: string): Product[] {
  return PRODUCTS.filter((p) => p.category.toLowerCase() === category.toLowerCase());
}

export function getProductsByCollection(collectionSlug: string): Product[] {
  return PRODUCTS.filter((p) => p.collection === collectionSlug);
}

export function getCollectionBySlug(slug: string) {
  return COLLECTIONS.find((c) => c.slug === slug);
}

export function categoryToSlug(category: string) {
  return category.toLowerCase().replace(/\s+/g, "-");
}

export function resolveCategoryFromSlug(slug: string) {
  const normalized = decodeURIComponent(slug).toLowerCase();
  return CATEGORIES.find(
    (c) => categoryToSlug(c) === normalized || c.toLowerCase() === normalized
  );
}
